### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by JustSteveKing** [TomasVotruba/punchcard#25]
There are times when you want to be able to add your own custom configuration to extend part of what you get out of the box with Laravels configuration. In fact, if you want to use Socialite - it looks in services.* for the OAuth connection configurations.

To achieve this and allow more custom configurations, I would maybe look to add a `custom` method to the configuration classes so that it is easier to manage and more flexible all in all.

```php
return ServicesConfig::make()
    // defaults here
    ->custom([
        'my-service' => []
    ])
    ->toArray();
```

**Comment by JustSteveKing** [comment]
> efinitely would need a way to put in custom values. Here is an example from the doc

I like this idea!

**Comment by TomasVotruba** [comment]
I'm looking into this...

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/TomasVotruba/punchcard/pull/28

Let me know, how it works for you :slightly_smiling_face:

**Comment by innocenzi** [comment]
@TomasVotruba I just tested that, sounds great but `service` currently doesn't return `$this` so we can't chain `toArray` on it 😔

**Comment by TomasVotruba** [comment]
Ups, what a bug. My bad :) I'll add it

**Comment by TomasVotruba** [comment]
@innocenzi Is fixed now and tagged :+1: 

https://github.com/TomasVotruba/punchcard/blob/cce731e012ec84dc329dbea59fd1bb11f54510bc/generated/ServicesConfig.php#L14-L18

**Comment by innocenzi** [comment]
Awesome, thank you!

**Comment by TomasVotruba** [comment]
Closing as resolved :tada:
