### ISSUE TITLE
Better service provider config

### ISSUE THREAD

**Issue by innocenzi** [TomasVotruba/punchcard#29]
Currently, the `app.php` config looks like that when you need to override the default service providers:

```php
return AppConfig::make()
    ->providers(ServiceProvider::defaultProviders()->merge([
        Infrastructure\Providers\AppServiceProvider::class,
        Infrastructure\Providers\AuthServiceProvider::class,
        Infrastructure\Providers\BroadcastServiceProvider::class,
        Infrastructure\Providers\EventServiceProvider::class,
        Infrastructure\Providers\RouteServiceProvider::class,
    ])->toArray())
    ->toArray();
```

I was thinking it would be nice to have it this way instead:

```php
return AppConfig::make()
    ->providers([
        Infrastructure\Providers\AppServiceProvider::class,
        Infrastructure\Providers\AuthServiceProvider::class,
        Infrastructure\Providers\BroadcastServiceProvider::class,
        Infrastructure\Providers\EventServiceProvider::class,
        Infrastructure\Providers\RouteServiceProvider::class,
    ])
    ->toArray();
```

This implies that `ServiceProvider::defaultProviders()` would be called internally and that `->providers` would call `merge` instead of overriding the whole list of providers.

What do you think?

**Comment by TomasVotruba** [comment]
Hi, I'm bothered by this one as well :)

The question is:
* sometimes we want to use just 3 provides, explicit and defined
* sometimes we want to use the default + app service one + few custom ones

How would you separate it via API?

**Comment by innocenzi** [comment]
I'm thinking adding a `withDefaultProviders` that would add the default ones:

```php
\App\Providers\AppServiceProvider::class,
\App\Providers\AuthServiceProvider::class,
// App\Providers\BroadcastServiceProvider::class,
\App\Providers\EventServiceProvider::class,
\App\Providers\RouteServiceProvider::class,
```

If one needs to exclude some of these, they would just not call `withDefaultProviders`, or call `withoutDefaultProviders`?

```php
return AppConfig::make()
    ->withoutDefaultProviders()
    ->withoutProviders([
        \Illuminate\Translation\TranslationServiceProvider::class
    ])
    ->withProviders([
        Infrastructure\Providers\AppServiceProvider::class,
        Infrastructure\Providers\AuthServiceProvider::class,
        Infrastructure\Providers\BroadcastServiceProvider::class,
        Infrastructure\Providers\EventServiceProvider::class,
        Infrastructure\Providers\RouteServiceProvider::class,
    ])
    ->toArray();

```

And maybe a more flexible `withoutProviders` that would remove the specified providers, default or not.

**Comment by TomasVotruba** [comment]
I see :+1:  I think the config should be opt-in, as that's how other configs behave.

This method makes most sense:

```php
->withoutDefaultProviders()
```

Ah, the default service provider is a new thing from: https://github.com/laravel/laravel/pull/6159/

Cool :)

**Comment by TomasVotruba** [comment]
Looking at the API again, I think it's better to use the `ServiceProvider::defaultProviders()` as it already offers explicitly everything we need. Making another layer would copy-paste the API.

**Comment by innocenzi** [comment]
I understand. Thank you for looking into it anyway!
